name: SonarQube Cloud Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # better issue tracking on PRs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # (Optional) install dependencies if your repo needs them for analysis hooks
      # - name: Install deps
      #   run: pip install -r requirements.txt

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
