name: SonarCloud Scan (CLI)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install sonar-scanner
        run: npm install -g sonar-scanner

      - name: Run SonarCloud Scan
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Bandit (Python SAST)
        run: |
          pip install bandit
          bandit -r . -x venv,.venv -f json -o bandit-report.json || true

      - name: Run Semgrep (OWASP rules)
        run: |
          # Semgrep
          pip install semgrep
          semgrep --config semgrep_rules.yaml \
                  --exclude venv \
                  --exclude .venv \
                  --exclude __pycache__ \
                  . --json > semgrep-report.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            semgrep-report.json